repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-json
      - id: check-yaml
      - id: detect-private-key

  - repo: local
    hooks:
      - id: lint
        name: ESLint
        entry: npm run lint
        language: system
        types: [javascript, typescript]
        pass_filenames: false

      - id: format
        name: Prettier
        entry: npm run format
        language: system
        types: [javascript, typescript, json, markdown]
        pass_filenames: false

      - id: type-check
        name: TypeScript
        entry: npm run type-check
        language: system
        types: [typescript]
        pass_filenames: false

      - id: test
        name: Unit Tests
        entry: npm run test
        language: system
        pass_filenames: false
