name: Quality Check
on:
  pull_request:
    branches: [main, develop, preview]
  push:
    branches: [main, develop, preview]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Type checking
        run: npm run type-check
        working-directory: ./apps/web

      - name: Linting
        run: npm run lint
        working-directory: ./apps/web

      - name: Unit tests
        run: npm run test
        working-directory: ./apps/web

      - name: Build verification
        run: npm run build
        working-directory: ./apps/web

  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: snyk.sarif
