name: Deploy to Preview
on:
  push:
    branches: [preview, develop]
  pull_request:
    branches: [main, develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run quality checks
        run: |
          npm run lint
          npm run type-check
          npm run test
          
      - name: Build application
        run: npm run build
        
      - name: Deploy to Vercel Preview
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          working-directory: ./
          vercel-args: '--env DATABASE_URL=${{ secrets.PREVIEW_DATABASE_URL }}'
          
      - name: Update Linear with Preview
        if: success()
        uses: linear/action@v1
        with:
          api-key: ${{ secrets.LINEAR_API_KEY }}
          comment: |
            🧪 **Preview Deployment Complete**
            
            **Branch**: `${{ github.ref_name }}`
            **Commit**: ${{ github.sha }}
            **Status**: ✅ Successfully deployed
            **Environment**: Preview/Staging
            **Preview URL**: ${{ steps.deploy.outputs.preview-url }}
