name: Deploy to Preview
on:
  push:
    branches: [preview, develop]
  pull_request:
    branches: [main, develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run quality checks
        run: |
          npm run lint
          npm run type-check
          npm run test
          
      - name: Build application
        run: npm run build
        
      - name: Deploy to Vercel Preview
        id: deploy
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          working-directory: ./
          vercel-args: '--env DATABASE_URL=${{ secrets.PREVIEW_DATABASE_URL }}'
          
      - name: Notify Preview Deployment
        if: success()
        run: |
          echo "🧪 Preview Deployment Complete"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          echo "Status: ✅ Successfully deployed"
          echo "Environment: Preview/Staging"
          echo "Preview URL: ${{ steps.deploy.outputs.preview-url }}"
